site_name: Microcraft
site_url: http://microcraft.edwardrolinsen.com
site_description: Microcraft™ Development Series.
site_author: Dreamtowards

repo_url: https://github.com/Dreamtowards/Microcraft
edit_uri: ""

theme: mkdocs

pages:
  - Home: index.md
  - Epsoids:
      - "Microcraft E1, Window Init.": microcraft-e1.md
      - Microcraft E2, The Triangle.: microcraft-e2.md
      - Microcraft E3, Quad, Texture, View, Camera.: microcraft-e3.md


markdown_extensions:
  - admonition

docs_dir: 'docs'

copyright: Copyright &copy; 2021 Someone